In [ ]:
#VIDHYASHREE G S -AMB2292

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset=pd.read_csv("/content/Product_purchase (1).csv")
print(dataset)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [ ]:
x=dataset.iloc[:,[2,3]].values
y =dataset.iloc[:,4].values

In [ ]:
print(dataset.columns[[2,3]])
print(dataset.columns[4])

Index(['Age', 'EstimatedSalary'], dtype='object')
Purchased


In [ ]:
#splitting the dataset into training set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)


In [ ]:
#decision tree
#createa decision tree classifier object
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_depth=None,min_samples_split=5,min_samples_leaf=2)
model.fit(x_train,y_train)  #training the model
print(model)
y_pred_dec=model.predict(x_test)#predicting the model
print(y_pred_dec)
from sklearn.metrics import confusion_matrix# making the confusion matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_dec))



DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)
[0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 1 1 1]
[[63  5]
 [ 6 26]]
0.89


In [ ]:
# createa object of the algorithum
from sklearn.linear_model import LogisticRegression
modellr=LogisticRegression(random_state=0)
modellr.fit(x_train,y_train)
print(modellr)
y_pred_lr=modellr.predict(x_test)#predicting the model
print(y_pred_lr)
from sklearn.metrics import confusion_matrix# making the confusion matrix
cmlr=confusion_matrix(y_test,y_pred_lr)
print(cmlr)
from sklearn.metrics import accuracy_score
print("Logistic Regression",accuracy_score(y_test,y_pred_lr))




LogisticRegression(random_state=0)
[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1]
[[65  3]
 [ 8 24]]
Logistic Regression 0.89


In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(n_estimators=100, random_state=0)
model_rf.fit(x_train, y_train)

y_pred_rf = model_rf.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm_rf = confusion_matrix(y_test, y_pred_rf)
print("Random Forest Confusion Matrix:")
print(cm_rf)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

Random Forest Confusion Matrix:
[[63  5]
 [ 3 29]]
Random Forest Accuracy: 0.92


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
social_network=pd.read_csv("/content/Product_purchase (1).csv")
print(social_network)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train,y_train)
y_pred_nb = nb.predict(x_test)
cmnb = confusion_matrix(y_test, y_pred_nb)
print(cmnb)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("accuracy:", accuracy_nb)

[[65  3]
 [ 7 25]]
accuracy: 0.9


In [ ]:
#support vector machine(svm)-regression and classification
from sklearn.svm import SVC   #svc-classification svr-regression
#create svm classifier object
#model = SVC(kernel='rbf',c=1.0,gamma='scale',random_state=0)
#model=SVC(kernel='linear')#hyperparameter tuning
model=SVC(kernel='poly',degree=3)
#model=svc(kernel='rbf')
#training the model
model.fit(x_train,y_train)
print(model)


SVC(kernel='poly')


In [ ]:
#predicting the test set results
y_pred_svm=model.predict(x_test)
print(y_pred_svm)


[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0]


In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm_svm=confusion_matrix(y_test,y_pred_svm)
print(cm_svm)

[[67  1]
 [13 19]]


In [ ]:
#accuracy