In [ ]:
import numpy as mp
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('Product_purchase.csv')

In [ ]:
dataset

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [ ]:
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values
print(x)
print(y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [ ]:
print(dataset.columns[[2,3]])
print(dataset.columns[4])

Index(['Age', 'EstimatedSalary'], dtype='object')
Purchased


In [8]:
#splitting data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [9]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [16]:
#decision tree
#create decision tree classifier object

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_depth=None,min_samples_split=5,min_samples_leaf=2)

model.fit(x_train,y_train) #training the model
print(model)

y_pred_dec=model.predict(x_test)#predict the testing model
y_pred_dec

from sklearn.metrics import confusion_matrix #making the confusion matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)


from sklearn.metrics import accuracy_score
print("decision tree",accuracy_score(y_test,y_pred_dec))

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)
[[66  2]
 [ 6 26]]
decision tree 0.92


In [17]:
#decision tree
#create an object of the algorithm or model

from sklearn.linear_model import LogisticRegression
modellr=LogisticRegression(random_state=0)

modellr.fit(x_train,y_train) #training the model
print(modellr)

y_pred_lr=modellr.predict(x_test)#predict the testing model
y_pred_lr

from sklearn.metrics import confusion_matrix #making the confusion matrix
cmlr=confusion_matrix(y_test,y_pred_lr)
print(cmlr)


from sklearn.metrics import accuracy_score
print("logisticregression",accuracy_score(y_test,y_pred_lr))

LogisticRegression(random_state=0)
[[65  3]
 [ 8 24]]
logisticregression 0.89


In [18]:
#fitting the classifier into the training set
from sklearn.ensemble import RandomForestClassifier
RFmodel=RandomForestClassifier(n_estimators=200,criterion='entropy',random_state=0)
RFmodel.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)

In [20]:
#Predicting the test set results
y_pred_rf=RFmodel.predict(x_test)
y_pred_rf

from sklearn.metrics import confusion_matrix
cmrf=confusion_matrix(y_test,y_pred_rf)
print(cmrf)

from sklearn.metrics import accuracy_score
print("random forest",accuracy_score(y_test,y_pred_rf))

[[64  4]
 [ 4 28]]
random forest 0.92
