In [ ]:
  import numpy as np
  arr=np.array([0,1,2,3])     #number of bracket represents dimensions
  print(arr)

[0 1 2 3]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr.dtype       # numpy stores dtype 64

dtype('int64')

In [ ]:
arr.shape #4 is element and dimension

(4,)

In [ ]:
arr.itemsize  #bytes per element

8

In [ ]:
arr.ndim   # dimension

1

In [ ]:
arr.nbytes   #bytes=no of element *8

32

In [ ]:
a=np.array([[0,1,2,3,],[10,11,12,13]])
print(a)                                #multidimensional array

[[ 0  1  2  3]
 [10 11 12 13]]


In [ ]:
a.shape   #(rows, columns)

(2, 4)

In [ ]:
a.size    #number of elements

8

In [ ]:
a.ndim

2

In [ ]:


a[1,3] =-1
print(a)


[[ 0  1  2  3]
 [10 11 12 -1]]


In [ ]:
a[1]             #address the 2nd row through single index

array([10, 11, 12, -1])

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
arr = np.array(2)
print(arr)
print(arr.size)           #0 dimensional array
print(arr.shape)
print(type(arr))
nd = arr.ndim
print("number of dimensions:",nd)

2
1
()
<class 'numpy.ndarray'>
number of dimensions: 0


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.size)
print(type(arr))
nd=arr.ndim
print("number of dimensions:",nd)           # 1D array

[1 2 3 4 5]
(5,)
5
<class 'numpy.ndarray'>
number of dimensions: 1


In [ ]:
arr=np.array([[1,2,8],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
print(arr.size)
print(type(arr))              #2 d array
nd=arr.ndim
print("number of dimensions:",nd)


[[1 2 8]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
<class 'numpy.ndarray'>
number of dimensions: 2


In [ ]:
arr=np.array([[1,2],[4,]])   # which gives value error no of elements should be same

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
arr=np.array ([[2.3,1],[1,2]])  # implict type of conversion integer is converted into floot
print(arr)
print(arr.shape)
print(arr.size)
print(type(arr))
nd=arr.ndim
print("number of dimensions:",nd)

[[2.3 1. ]
 [1.  2. ]]
(2, 2)
4
<class 'numpy.ndarray'>
number of dimensions: 2


In [ ]:
arr=np.array([ 1,2,3,4],ndmin=5)   # 1d is converted into 5d by using ndmin
print(arr)

[[[[[1 2 3 4]]]]]


In [ ]:
# array indexing
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
# write a prg to calculate 3rd and 4 th element
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])     # here 2 and 3 are index number

7


In [ ]:
#create a dimention array of size 2*5 access 2nd element on 1st dimension
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st dimension:",arr[0,1])  #index

2nd element on 1st dimension: 2


In [ ]:
#access 3rd element of 2nd array
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)
print("3rd element of 2nd array:",arr[0, 1,2])


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
3rd element of 2nd array: 6


In [ ]:
#python prg to perform basic arithmatic operation using 1D array
arr=np.array([1,3,5,7,9])
sum=arr[0]+arr[2]
diff=arr[3]-arr[2]
pro=arr[1]*arr[3]
div=arr[4]/arr[2]
print("sum of 2 numbers:",sum)
print("difference of 2 numbers:",diff)
print("product of 2 numbers:",pro)
print("division of 2 numbers:",div)

sum of 2 numbers: 6
difference of 2 numbers: 2
product of 2 numbers: 21
division of 2 numbers: 1.8


In [ ]:
# slicing 1D array
arr=np.array([2,4,6,8,10,12,14,16])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])
print(arr[:-1])

[ 8 10 12]
[ 2  4  6  8 10]
[ 6  8 10 12 14 16]
[ 8 10 12 14]
[ 2  4  6  8 10 12 14]


In [ ]:
# slicing 2D array
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
# copy method
arr= np.array([1,2,3,4,5])   # copy method does not change original array
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# resizing
array= np.array([[1,2,3],[4,5,6]])
print(array)
print(array(3,2))

[[1 2 3]
 [4 5 6]]


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12], ndmin=2)
print(arr)
newarr=arr.reshape(2,3,2)       #reshape
print(newarr)


[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,14,4)

array([ 1,  5,  9, 13])

In [ ]:
#elements of airthematic operation
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1 @ arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [ ]:
concatenated_arr=np.concatenate((arr1,arr2),axis=0)#concatenate along rows
print(concatenated_arr)
print()
concatenated_arr=np.concatenate((arr1,arr2),axis=1)#concatenate along columns
print(concatenated_arr)
transpose_array=np.transpose(arr1)  #transpose interchange of rows and columns
print(transpose_array)
flattened_array=arr1.flatten()#flattened multidimensional to single dimension
print(flattened_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
a=np.array([1+1j,1+0j,4.5,3,2,2j])
print(a)
print("checking the complex number:")   # complex is dominated
print(np.iscomplex(a))
print("checking the real number:")
print(np.isreal(a))
print("checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
checking the complex number:
[ True False False False False  True]
checking the real number:
[False  True  True  True  True False]
checking for scalar type:
True
False


In [ ]:
arr=np.zeros(3)   #it creates floot

print(arr)

[0. 0. 0.]


In [ ]:
arr=np.ones(3)
print(arr)

[1. 1. 1.]


In [ ]:
empty1=np.empty([2,3])
print(empty1)

[[1.00125028e-315 0.00000000e+000 6.61681798e-310]
 [6.61681798e-310 6.61681803e-310 6.61681804e-310]]


In [ ]:
import numpy as np
 #crop yield for 4 farms over 5 seasons(in tons)
crop_yields=np.array([
    [12.5, 13.2,14.1,13.8, 15.2],
    [10.3, 11.5,10.8,12.1,11.9],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.3, 11.7,12.8]
])
print("crop yields array (tons):")
print(crop_yields)
print(f'/n shape:{crop_yields.shape}')
print(f'/n data type:{crop_yields.dtype}')
print(f'/n total elements:{crop_yields.size}')
print(f'/n num of dimensions:{crop_yields.ndim}')

crop yields array (tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]
/n shape:(4, 5)
/n data type:float64
/n total elements:20
/n num of dimensions:2


In [ ]:
# agricultural analysis operation
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)#along the rows
avg_yield_per_season=np.mean(crop_yields,axis=0) #along the columns
avg_yield_per_farm=np.median(crop_yields,axis=1)
avg_yield_per_season=np.median(crop_yields,axis=0)
avg_yield_per_farm=np.std(crop_yields,axis=1)
avg_yield_per_season=np.std(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'/n total production:{total_yield} tons')
print(f'avg per farm:{avg_yield_per_farm} tons')
print(f'avg per season:{avg_yield_per_season} tons')
print(f'max yield:{max_yield} tons')
print(f'min yield:{min_yield} tons')


NameError: name 'np' is not defined

In [ ]:
best_farm=np.argmax(avg_yield_per_farm)  #index of maximum value
print(f'/n best performing farm:farm',best_farm+1) # index start from 0 thats y +1 added
print("their avg yield is:", round (avg_yield_per_farm[best_farm],2),"tons")

print(f'/n best performing farm:farm {best_farm+1}')
print(f'/n their avg yield is:{avg_yield_per_farm[best_farm]:.2f} tons')




/n best performing farm:farm 1
their avg yield is: 0.9 tons
/n best performing farm:farm 1
/n their avg yield is:0.90 tons


In [ ]:
median_yield=np.median(crop_yields)
print(f'/n median yield:{median_yield} tons')
std_yield=np.std(crop_yields)
print(f'/n standard deviation of yield:{std_yield} tons')

/n median yield:12.65 tons
/n standard deviation of yield:1.890310821002726 tons


In [ ]:
#conditional operations:classify yields
categories=np.where(crop_yields>16,'high',
                    np.wh)
